# Generated by Django 5.0.3 on 2024-05-12 02:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlabs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='start_time',
        ),
        migrations.AddField(
            model_name='bookings',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
