# Generated by Django 5.0.3 on 2024-05-12 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlabs', '0002_remove_bookings_end_time_remove_bookings_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='lab',
        ),
        migrations.AddField(
            model_name='bookings',
            name='computer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vlabs.computer'),
            preserve_default=False,
        ),
    ]
